### ISSUE TITLE
things to add to the lessons (by popular demand)

### ISSUE THREAD

**Issue by drtortoise** [CodeClub/webdev-curriculum#2]
- [ ] how to make and add favicons
- [ ] make a blog from scratch (!) bit more effort there
- [ ] more on layouts
- [ ] bugfixing/cascade/specificity and the magic of !important *ugh*

**Comment by rikcross** [comment]
I'll close this issue now, as the new projects do (or will) cover everything here except favisons, which aren't possible in Trinket.
