### ISSUE TITLE
flowers.png missing from “Happy Birthday” resources

### ISSUE THREAD

**Issue by andylolz** [CodeClub/webdev-curriculum#30]
flowers.png is mentioned in the lesson (and works in trinket) but it’s missing from [the project resources](https://github.com/CodeClub/webdev-curriculum/tree/89152941/en-GB/Happy%20Birthday/Project%20Resources).

**Comment by CodeClubRik** [comment]
Cheers @andylolz !

**Comment by andylolz** [comment]
Great – thanks, @CodeClubRik :)
Here’s a gallery of the cards we made: http://web.treadsoft.ly/kuv
