### ISSUE TITLE
Happy Birthday: “Hover to open” was tricky to use

### ISSUE THREAD

**Issue by andylolz** [CodeClub/webdev-curriculum#31]
It’s possible this was due to the version of Chrome we were using, but the club members found the “hover to open” interface difficult to use.

Click to open / click to close might be easier to use.

**Comment by CodeClubRik** [comment]
> Click to open / click to close might be easier to use.
I agree completely. Is that easy to implement? Does that involve toggling the class of the front onclick?

**Comment by andylolz** [comment]
> Does that involve toggling the class of the front onclick?

Yeah – that sounds like a good method. Here’s a working version:
https://trinket.io/library/trinkets/ab215ca888
