### ISSUE TITLE
Move CSS into a separate file in Trinket

### ISSUE THREAD

**Issue by andylolz** [CodeClub/webdev-curriculum#32]
Trinket lets you create and reference separate files. Here, I’ve moved the embedded styles into a file called styles.css and referenced it:

![trinket](https://cloud.githubusercontent.com/assets/464193/8352465/3c024e4e-1b2d-11e5-90b4-cda2eb40179e.png)

I think this is an improvement for a number of reasons (shorter files; separation of style and content; better practice). It also means you get CSS linting (which you don’t get for embedded styles) e.g.:

![screen shot 2015-06-25 at 10 37 40](https://cloud.githubusercontent.com/assets/464193/8351569/43e3b334-1b26-11e5-900a-c5bd73dacf7a.png)

The CSS in the first lesson is pretty complicated, and when one club member made an error that prevented his card from opening (changing `:hover` for `:flowers`) neither of us was able to spot the error. With a linter, we’d have spotted it straight away.

**Comment by andylolz** [comment]
I’m not able to make this change, since it requires access to the trinket account that owns the projects.

**Comment by CodeClubRik** [comment]
No problem -- I'll get to this soon. It involves altering text etc. in the project too.

**Comment by andylolz** [comment]
Yep, true. I’m happy to send a pull request for that?

**Comment by CodeClubRik** [comment]
I will try and work out this birthday card 'click-to-open' thing first, and then update the project text, so that we're not making two lots of improvements to the project notes.

**Comment by andylolz** [comment]
> we're not making two lots of improvements to the project notes

Why is this bad? Do you mean because the project would change twice? If so, note that the live project only changes when a pull request from @codeclubrobot is merged. So if you hold off on merging, you can make several updates at once.

**Comment by CodeClubRik** [comment]
I just meant that I may as well update the trinket before updating the project, as line numbers, etc. would change. However, I notice you've already submitted a PR for that! :+1:

**Comment by CodeClubRik** [comment]
...also, a few other things will change, such as the downloadable offline resources, and the 'guide to working offline' etc. I'll have a look at these today :)

**Comment by andylolz** [comment]
Gah – making these updates in an atomic way is complicated! There are a lot of things to update!

> I just meant that I may as well update the trinket before updating the project

I’d suggest doing the opposite of this – i.e. updating the project first, _then_ the trinket. That’s because the trinket can be updated quickly and easily, whereas the other stuff is a bottleneck. Currently, the project is partially updated – the trinket has been updated, but the rest of the project hasn’t. If anyone is running a club with this today, that’s likely to cause some confusion.

**Comment by CodeClubRik** [comment]
Completely agree - I'll merge your PR first, and then make a few additional changes and finally change the trinket.

The live project currently matches the trinket -- so I'll not update the trinket until the project changes are live.

> the trinket has been updated

I haven't updated the trinket yet, so nothing should be out of sync yet. If you're seeing a new multi-tab project, it's just because you're viewing your remix and not the original trinket.

**Comment by andylolz** [comment]
> It's just because you're viewing your remix and not the original trinket.

Sorry! You’re absolutely right. That catches me out every time!

**Comment by CodeClubRik** [comment]
Me too -- I'll bring it up with them.

**Comment by andylolz** [comment]
Right – I’ve updated the resources for that project now (in the same PR).

**Comment by CodeClubRik** [comment]
thanks!

**Comment by CodeClubRik** [comment]
> Gah – making these updates in an atomic way is complicated! There are a lot of things to update!

The only way I can think to solve this is by creating and referencing new trinkets in a new version, so that everything goes live at the same time.

I've merged your PR for the first project, and I'll close this once i've updated the other projects, the trinkets and the guide to working offline.

**Comment by andylolz** [comment]
> The only way I can think to solve this is by creating and referencing new trinkets in a new version, so that everything goes live at the same time.

Can do, yep… But if people have printed the material, they’d still end up at the old trinket. It’s probably better to do two steps, and update the jumpto.cc link to point to the new trinket (assuming they’re mutable). Shortlinks have a habit of becoming stale (which is why using immutable ones like bit.ly can be bad) so if you can avoid that, that’s probably preferable.

> I'll close this once i've updated the other projects

Cool – sounds good. I can send a PR for “Tell a Story” today, since we’re doing that project at Code Club this afternoon. (I’m looking forward to it – it looks like a good one!)

**Comment by martinpeck** [comment]
FYI we don't use bit.ly any more, for that exact reason.

**Comment by CodeClubRik** [comment]
Exactly @martinpeck - we can update the short links too. However, we lose trinket stats if I keep switching trinkets around, which is a shame.

**Comment by andylolz** [comment]
> we lose trinket stats if I keep switching trinkets around

That’s true. Well… Updating the trinket (rather than the shortlink) would also be fine (and would maintain the trinket stats).

**Comment by andylolz** [comment]
:rocket:
