### ISSUE TITLE
Happy Birthday: Make first task birthday-related

### ISSUE THREAD

**Issue by andylolz** [CodeClub/webdev-curriculum#33]
The first task in _Happy Birthday_ involves modifying the following text:

> This is a paragraph of text.
>
> Here is another paragraph, with __bold__ and _italics_.

It’s fine, but it’s a bit dry. I changed it to:

> My name is Andy
> 
> I like __running__ and _riding my bike_.

…and asked the children to modify that (Daisy likes __maths__ and _fashion_). Even better would be to make it birthday-related. Could even use the `<sup>` tag e.g. My birthday is 22<sup>nd</sup> December.

**Comment by andylolz** [comment]
Nice!

**Comment by CodeClubRik** [comment]
I left your name in, as a tribute.
Feel free to change the name if you don't think you can handle the fame.

**Comment by andylolz** [comment]
Haha! Related: I’m really looking forward to Fatma and Nadia seeing their joke in the Tell A Story project!

**Comment by CodeClubRik** [comment]
:+1:
