### ISSUE TITLE
Cards for new projects.

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/webdev-curriculum#39]
There are 3 new projects that I'd like to add the the webdev curriculum:

+ Recipe;
+ Build a Robot;
+ Hall of Fame.

I had a go at producing a card for 'recipe', as i was interested to see how everything worked (feel free to amend/delete!):

![small_banner](https://cloud.githubusercontent.com/assets/7372432/9787155/086c4a7c-57b8-11e5-8cfa-ac7065bd942e.png)

The images for the other projects are in dropbox:

+ Broken Robot
+ Fame Star

Thanks,
Rik.

**Comment by gregorywood** [comment]
The recipe one looks grand, here are the other two. I'll push them up to the repo shortly

![image](https://cloud.githubusercontent.com/assets/881722/9851208/6abaf6d0-5aef-11e5-81b7-f534c146d3f4.png)

![image](https://cloud.githubusercontent.com/assets/881722/9851202/60466144-5aef-11e5-8880-53339c2ec334.png)

**Comment by CodeClubRik** [comment]
Cheers @gregorywood

**Comment by CodeClubRik** [comment]
I'll add the robot one myself now -- we can't upload the 'hall of fame' card because the project doesn't exist in the repo yet!
