### ISSUE TITLE
fix "saving your work" directory diagrams

### ISSUE THREAD

**Issue by drtortoise** [CodeClub/webdev-curriculum#7]
![screen shot 2014-02-19 at 16 14 29](https://f.cloud.github.com/assets/201994/2208550/0bca51e2-9981-11e3-8362-c03fdbb3e43d.png)

**Comment by CodeClubRik** [comment]
I should add something like this to the 'Working Offline' HTML&CSS section.

**Comment by rik-cross** [comment]
Closing this, as it forms part of another issue on updating the website 'resources' section.
